### ISSUE TITLE
Danke und Übungsklausuren

### ISSUE THREAD

**Issue by Dragonexodus** [maweki/ti-tutorium16#1]
Danke für das zur Verfügung stellen des Repos!
Hast du zufällig ältere Prüfungen von Herrn Petermann, welche du zur Verfügung stellen könntest?

LG

**Comment by maweki** [comment]
Das kann/mache ich nicht. Im "berühmten" Dropbox-Share liegen allerdings Prüfungen von mindestens 2012 und 2014.
Die Fragen dort decken sich aber mit den Beispielfragen hier, da die Prüfung immer nach dem selben Schema abläuft mit den 4 Fragenkomplexen, genau wie im Repo angedeutet.

**Comment by Dragonexodus** [comment]
Okay!
Danke!
